extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:svelte/prettier'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  project:
    - './tsconfig.json'
    - './tsconfig.node.json'
  extraFileExtensions:
    - '.svelte'
env:
  es6: true
  browser: true
overrides:
  - files:
    - '*.svelte'
    parser: 'svelte-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint/eslint-plugin'
ignorePatterns:
  - 'node_modules'
